question_data = [
    {"text": "The 'print()' function is used to output text to the screen in Python.", "answer": "True"},
    {"text": "Python lists are immutable.", "answer": "False"},
    {"text": "The 'len()' function returns the number of items in a list or the length of a string.", "answer": "True"},
    {"text": "Python dictionaries are unordered data structures.", "answer": "False"},
    {"text": "The 'break' statement is used to exit a loop prematurely.", "answer": "True"},
    {"text": "Python is a functional programming language.", "answer": "False"},
    {"text": "The 'try-except' block is used for error handling in Python.", "answer": "True"},
    {"text": "Python is a compiled language.", "answer": "False"},
    {"text": "The 'range()' function generates a sequence of numbers.", "answer": "True"},
    {"text": "Python sets are ordered collections of unique elements.", "answer": "False"},
    {"text": "The 'lambda' keyword is used to create anonymous functions in Python.", "answer": "True"},
    {"text": "Python supports single inheritance only.", "answer": "False"},
    {"text": "The 'with' statement is used for exception handling when working with files.", "answer": "True"},
    {"text": "Python's 'None' type represents a null or undefined value.", "answer": "True"},
    {"text": "The 'enumerate()' function returns a list containing a count and the values obtained from iterating over a sequence.", "answer": "False"},
    {"text": "Python's 'zip()' function aggregates elements from multiple iterables.", "answer": "True"},
    {"text": "The 'super()' function is used to access the methods of a parent class.", "answer": "True"},
    {"text": "Python's 'map()' function applies a given function to each item of an iterable.", "answer": "True"},
    {"text": "The 'filter()' function constructs a list from elements of an iterable for which a function returns True.", "answer": "False"},
    {"text": "Python's 'sorted()' function returns a new sorted list from the elements of any sequence.", "answer": "True"},
]